### ISSUE TITLE
Is there no way to get 'blink' and 'jaw clench' data stream?

### ISSUE THREAD

**Issue by iPsych** [alexandrebarachant/muse-lsl#35]
I am curious that is there any way to get t 'blink' and 'jaw clench' data stream?
If it calculated in the system using api, it might impossible...
I am wondering it's availability.

**Comment by hubertjb** [comment]
The blink and jaw clench streams are computed by the Muse SDK, which muse-lsl doesn't use. To get them you would need to use one of the solutions provided by Interaxon, like the SDK itself or Muse Direct: http://www.choosemuse.com/developer/ Otherwise, you could also develop your own on top of muse-lsl.
