### ISSUE TITLE
Electrodes

### ISSUE THREAD

**Issue by BogdanI12** [alexandrebarachant/muse-lsl#74]
Hello,

Thank you for the code, it worked at the first try.

I looked over it and i have a question:
- INDEX_CHANNLE is 0, at first, for the left_ear electrode, if i change it and check the Alpha Wave i get different values, which makes sense.

But is there some "configuration" to know which electrode is for which wave ?
For example: to know that if i use the one on the right ear I will get accurate data for Theta wave, or something like that.

Thank you again.

**Comment by jdpigeon** [comment]
Hey @BogdanI12, 

If I understand your question correctly, you are interested in knowing which electrode to analyze in order to observe different meaningful brain rhythms?

This is mostly a neuroscience question and the answer of which electrodes you will want to use for your analysis may vary depending on what questions you are trying to answer/what kind of experience you are trying to develop. For instance, some EEG measures of engagement and attention seem to be most clearly detectable at frontal electrodes, so AF7/AF8 and electrodes 1 and 2 in muse LSL.

However, I can say that we have had the most success using the temporal electrodes from the Muse for running simple BCIs and neurofeedback interfaces based on alpha and theta waves. This is partly because the source of those rhythms is thought be located more medially in the brain, but also because the placement of the reference sensor in the Muse allows signals at the temporal electrodes to be picked up with more clarity.

Let me know if this answers your question!
